### PR TITLE
Lab 2B_proposal: Ying Xu  worked with: Sizhe Ma&Sudong Wang

### PR DESCRIPTION
**Pull request by real-YingXu**
Sizhe Ma and Sudong Wang helped me a lot in the process of connecting  the circuit.

### CODE REVIEW

**Comment by real-YingXu** [comment]
[
](https://github.com/real-YingXu/ese5190-2022-lab2b-esp/blob/main/README.md)

**Review by pixelflipping — CHANGES_REQUESTED** [review]
thanks; resubmit with only a link added to the repo (https://github.com/ese-detkin-lab/ese5190-2022-lab2b-esp)

**Comment by real-YingXu** [comment]
> thanks; resubmit with only a link added to the repo (https://github.com/ese-detkin-lab/ese5190-2022-lab2b-esp)

professor,I edit the readme file ,but it still has the conflicts.
My  readme.file  link is https://github.com/real-YingXu/ese5190-2022-lab2b-esp/blob/main/README.md

**Comment by real-YingXu** [comment]
Dear professor,

I edit the readme file ,but it still has the conflict.
My readme.file link is
https://github.com/real-YingXu/ese5190-2022-lab2b-esp/blob/main/README.md


Sincerely，
Ying Xu

**Comment by pixelflipping** [comment]
> Dear professor, I edit the readme file ,but it still has the conflict. My readme.file link is https://github.com/real-YingXu/ese5190-2022-lab2b-esp/blob/main/README.md Sincerely， Ying Xu

ok, you will want to do the proposal in your own separate repository (e.g., https://github.com/MaxMa6150/LAB2B_Proposal/)

then to submit, you will fork the lab2b repo, add a link to your proposal repo to the 'dashboard', and create a pull request with your edited link (e.g., https://github.com/ese-detkin-lab/ese5190-2022-lab2b-esp/pull/7/files)

**Comment by real-YingXu** [comment]
Thank you so much,I have changed it successfully.

https://github.com/real-YingXu/ese5190-2022-lab2b-esp

https://github.com/real-YingXu/Ying-Xu_lab2b_proposal/blob/main/README.md

**Pull request closed without merging**
